### ISSUE TITLE
WorkflowManagerActor: Workflow f5905e43-a5fe-423c-be74-3afbfc0d5540 failed 

### ISSUE THREAD

**Issue by khsjh** [broadinstitute/epi-SHARE-seq-pipeline#82]
When I running dockstore, I got this error message

 [info] WorkflowManagerActor: Workflow f5905e43-a5fe-423c-be74-3afbfc0d5540 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.Mater
ializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Failed to evaluate input 'read2_atac' (reason 1 of 1): No coercion defined from '"/home/younso/dockstore_test/cromwell-input/23968040-60bc-49a0-81a3-be2416675905/home/younso/scRNA/share-raw/sp.atac.R1.fastq.gz"
' of type 'spray.json.JsString' to 'Array[File]'.
Failed to evaluate input 'read1_rna' (reason 1 of 1): No coercion defined from '"/home/younso/dockstore_test/cromwell-input/23968040-60bc-49a0-81a3-be2416675905/home/younso/scRNA/share-raw/sp.rna.R1.fastq.gz"'
of type 'spray.json.JsString' to 'Array[File]'.
Failed to evaluate input 'save_plots_to_dir' (reason 1 of 1): No coercion defined from 'true' of type 'spray.json.JsTrue$' to 'String'.
Failed to evaluate input 'read1_atac' (reason 1 of 1): No coercion defined from '"/home/younso/dockstore_test/cromwell-input/23968040-60bc-49a0-81a3-be2416675905/home/younso/scRNA/share-raw/sp.atac.R2.fastq.gz"
' of type 'spray.json.JsString' to 'Array[File]'.
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFail
ed(MaterializeWorkflowDescriptorActor.scala:257)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:227)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:222)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at akka.actor.FSM.processEvent(FSM.scala:707)
        at akka.actor.FSM.processEvent$(FSM.scala:704)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:169)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:847)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:829)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:169)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:701)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:695)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:169)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
        at akka.actor.ActorCell.invoke(ActorCell.scala:583)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

my command is below

`dockstore workflow launch --entry github.com/broadinstitute/epi-SHARE-seq-pipeline/SHARE-seq:release --json test_Dockstore.json
`

and the information of test_Dockstore.json are

{
  "ShareSeq.gtf": "/home/younso/dockstore_test/hg19.genes.gtf",
  "ShareSeq.remove_single_umi": false,
  "ShareSeq.docker_image_dorcs": "/home/younso/bin/epi-SHARE-seq-pipeline/dockerfiles",
  "ShareSeq.maxFeature_RNA": "2500",
  "ShareSeq.read1_rna": "/home/younso/scRNA/share-raw/sp.rna.R1.fastq.gz",
  "ShareSeq.read2_rna": "/home/younso/scRNA/share-raw/sp.rna.R2.fastq.gz",
  "ShareSeq.corrPVal": "0.05",
  "ShareSeq.cpus_atac": "20",
  "ShareSeq.dorcs.chunkSize": "50000",
  "ShareSeq.joint.min_genes": "200",
  "ShareSeq.cpus_dorcs": "20",
  "ShareSeq.read2_atac": "/home/younso/scRNA/share-raw/sp.atac.R1.fastq.gz",
  "ShareSeq.cpus": "20",
  "ShareSeq.topNGene": "30",
  "ShareSeq.minCells_RNA": "3",
  "ShareSeq.idx_tar_atac": "/home/younso/dockstore_test/hg19.tar.gz",
  "ShareSeq.joint.min_umis": "50",
  "ShareSeq.include_multimappers": false,
  "ShareSeq.rna.umap_dim": "10",
  "ShareSeq.joint.mem_gb": "64",
  "ShareSeq.cutoff_rna": "100",
  "ShareSeq.minFeature_RNA": "200",
  "ShareSeq.multimappers": false,
  "ShareSeq.qc": false,
  "ShareSeq.idx_tar_rna": "/home/younso/dockstore_test/hg19.tar.gz",
  "ShareSeq.joint.min_frags": "100",
  "ShareSeq.genome_name_input": "hg19",
  "ShareSeq.percentMT_RNA": "5",
  "ShareSeq.dorcs.numBackgroundPairs": "100000",
  "ShareSeq.prefix": "shareseq-project",
  "ShareSeq.save_plots_to_dir": TRUE,
  "ShareSeq.joint.disk_gb": "50",
  "ShareSeq.rna.umap_resolution": "0.5",
  "ShareSeq.windowPadSize": "50000",
  "ShareSeq.dorcs.disk_gb": "100",
  "ShareSeq.fripCutOff": "0.3",
  "ShareSeq.cutoff_atac": "100",
  "ShareSeq.mem_gb_dorcs": "64",
  "ShareSeq.dorcs.numNearestNeighbor": "30",
  "ShareSeq.joint.umi_metrics_cutoff": "10",
  "ShareSeq.dorcGeneCutOff": "10",
  "ShareSeq.mode": "fast",
  "ShareSeq.read1_atac": "/home/younso/scRNA/share-raw/sp.atac.R2.fastq.gz",
  "ShareSeq.cpus_rna": "20",
  "ShareSeq.joint.min_tss": "4",
  "ShareSeq.include_introns": "true",
  "ShareSeq.gene_naming": "gene_name"
}

In test_Dockstore.json, there are almost contents of Dockstore.json except some features that I didn't know what should I fill
As I inferred, it seems that more than two paths should be entered in ShareSeq.read1_rna, but the example file contains only one path and there is only one pair of files.
Do I have to put both reads in read1 without caring about read1 and read2?

**Comment by sidwekhande** [comment]
Hi @khsjh,

Thank you for your interest in the pipeline!

The inputs for `read1_atac`, `read2_atac` and `read1_rna` need to be defined as Array[File] - for example, try using 
`ShareSeq.read1_rna": ["/home/younso/scRNA/share-raw/sp.rna.R1.fastq.gz"]`
For `save_plots_to_dir`, please try using `save_plots_to_dir = "true"`.

We are working to release a new version of the pipeline soon, and some of these inputs will be changed. You should not put read2 in ShareSeq.read1_rna - if you have multiple read1 files, you can pass them in as Array[File1, File2]. 
Hope this answers your question.
